spring:
  datasource:
    url: ${AUTH_DB_URL}
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${AUTH_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

server:
  port: ${AUTH_SERVICE_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    hostname: auth-service
    prefer-ip-address: false # IP 대신 호스트 이름 사용
    non-secure-port-enabled: true # HTTP를 사용하는 경우

service:
  jwt:
    access-expiration: 360000
    secret-key: ${JWT_SECRET_KEY}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

logging:
  level:
    root: info
    com.takeit: info
    org.springframework: warn
    org.hibernate.type.descriptor.sql: info
    org.hibernate.SQL: info