spring:
  datasource:
    url: ${AUTH_DB_URL}
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${AUTH_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

server:
  port: ${AUTH_SERVICE_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

service:
  jwt:
    access-expiration: 360000
    secret-key: ${JWT_SECRET_KEY}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}
  endpoint:
    health:
      show-details: when_authorized
    prometheus:
      enabled: true

logging:
  level:
    root: info
    com.takeit: info
    org.springframework: warn
    org.hibernate.type.descriptor.sql: info
    org.hibernate.SQL: info