plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.7' apply false
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.takeit'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

ext {
	set('springCloudVersion', "2023.0.4")
	set('querydslVersion', "5.0.0")
	set('jwtVersion', "0.12.6")
	set('postgresqlVersion', "42.7.4")
}

subprojects {
	apply plugin: 'java'
	apply plugin: 'org.springframework.boot'
	apply plugin: 'io.spring.dependency-management'

	repositories {
		mavenCentral()
	}

	dependencyManagement {
		imports {
			mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
		}
	}

	// 공통 의존성 관리
	dependencies {
		// Spring
		implementation 'org.springframework.boot:spring-boot-starter'

		// Lombok
		compileOnly 'org.projectlombok:lombok'
		annotationProcessor 'org.projectlombok:lombok'

		// Test
		testImplementation 'org.springframework.boot:spring-boot-starter-test'
		testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

		// Monitoring
		implementation 'org.springframework.boot:spring-boot-starter-actuator'
		runtimeOnly 'io.micrometer:micrometer-registry-prometheus'

		// Tracing
		implementation 'io.micrometer:micrometer-tracing-bridge-brave'
		implementation 'io.github.openfeign:feign-micrometer'
		implementation 'io.zipkin.reporter2:zipkin-reporter-brave'
	}

	tasks.named('test') {
		useJUnitPlatform()
	}
}
