spring:
  datasource:
    url: ${COUPON_DB_URL}
    username: ${COUPON_DB_USERNAME}
    password: ${COUPON_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${COUPON_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 10
    open-in-view: false

server:
  port: ${COUPON_SERVICE_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}