spring:
  application:
    name: gateway-service
  profiles:
    default: local
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auths/**,/api/v1/users/**,/api/v1/admins/**,/feign/v1/auths/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**,/feign/v1/orders/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**,/feign/v1/products/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**,/feign/v1/payments/**
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/v1/reviews/**,/feign/v1/reviews/**
        - id: coupon-service
          uri: lb://coupon-service
          predicates:
            - Path=/api/v1/coupons/**,/feign/v1/coupons/**
        - id: favorite-service
          uri: lb://favorite-service
          predicates:
            - Path=/api/v1/favorites/**,/feign/v1/favorites/**