server:
  port: 19091

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:19090/eureka/

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

logging:
  level:
    root: debug
    com.takeit: debug
    org.springframework: warn