server:
  port: ${GATEWAY_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    hostname: gateway
    prefer-ip-address: false # IP 대신 호스트 이름 사용
    non-secure-port-enabled: true # HTTP를 사용하는 경우

service:
  jwt:
    secret-key: $${JWT_SECRET_KEY}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

logging:
  level:
    root: info
    com.takeit: info
    org.springframework: warn