spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/takeit_payment
    username: takeit_payment
    password: takeit_payment
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 19095

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:19090/