spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/takeit_payment
    username: takeit_payment
    password: takeit_payment
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 19095

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
message:
  exchange: "takeit"
  queue:
    order:
      cancel: "takeit.order.cancel"
