### 리뷰 생성
POST /api/v1/reviews HTTP/1.1
Host: localhost:19096
X-Username: username
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="stars"

4
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="comment"

리뷰 코맨트
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="orderId"

b719e757-535a-407f-a75d-8861171739d6
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### 리뷰 수정
PUT /api/v1/reviews/1270f335-3493-4269-8d01-c711b3f283c7 HTTP/1.1
Host: localhost:19096
X-Username: username
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="stars"

3
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="comment"

수정된 코멘트
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="deleteFileNames"

361adf81-e160-4a0e-a5fc-215d450f1f2e, e4b17f53-5abb-42c4-8290-3e89a7bfa003
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### 리뷰 삭제
DELETE localhost:19096/api/v1/reviews/fcd7e1ab-ee37-40c4-b9da-f549facc64c1
Content-Type: application/json
X-Username: username

### 리뷰 상세 조회
GET localhost:19096/api/v1/reviews/fcd7e1ab-ee37-40c4-b9da-f549facc64c1
Content-Type: application/json
X-Username: username

### 리뷰 목록 조회
GET localhost:19096/api/v1/reviews
Content-Type: application/json
