spring:
  datasource:
    url: ${ORDER_DB_URL}
    username: ${ORDER_DB_USERNAME}
    password: ${ORDER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${ORDER_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

server:
  port: ${ORDER_SERVICE_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}
  endpoint:
    health:
      show-details: when_authorized
    prometheus:
      enabled: true