spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/takeit_order
    username: takeit_order
    password: takeit_order
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: redis-stack
      port: 6379
      password: systempass
  rabbitmq:
    host: rabbitMQ
    port: 5672
    username: guest
    password: guest

server:
  port: 19093

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:19090/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

message:
  exchange: "takeit"
  queues:
    order:
      cancel: "takeit.order.cancel"
      complete: "takeit.order.complete"
    product:
      cancel: "takeit.product.cancel"
    coupon:
      cancel: "takeit.coupon.cancel"
