spring:
  datasource:
    url: {ORDER_DB_URL}
    username: {ORDER_DB_USERNAME}
    password: {ORDER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: {ORDER_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        hibernate.type:
          trace: true # SQL에 바인딩된 파라미터 값을 출력
        default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.SQL: trace

server:
  port: {ORDER_SERVICE_PORT}

eureka:
  client:
    service-url:
      defaultZone: {EUREKA_SERVER_URL}