spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://postgres:5432/takeit_product
    username: takeit_product
    password: takeit_product
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 19094

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:19090/eureka/

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false