spring:
  application:
    name: eureka-server

server:
  port: ${EUREKA_SERVER_PORT}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: ${EUREKA_HOSTNAME}
