spring:
  application:
    name: eureka-server

server:
  port: ${EUREKA_SERVER_PORT}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: ${EUREKA_HOSTNAME}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}
  endpoint:
    health:
      show-details: when_authorized
    prometheus:
      enabled: true
