spring:
  application:
    name: eureka-server

server:
  port: 19090

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: eureka-server

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true