spring:
  application:
    name: review-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 10
    open-in-view: false
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    username: ${SPRING_DATASOURCE_LOCAL_USERNAME}
    password: ${SPRING_DATASOURCE_LOCAL_PASSWORD}
    url: ${SPRING_DATASOURCE_LOCAL_URL}

server:
  port: 19096

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

