spring:
  datasource:
    url: {REVIEW_DB_URL}
    username: {REVIEW_DB_USERNAME}
    password: {REVIEW_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: {REVIEW_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        hibernate.type:
          trace: true # SQL에 바인딩된 파라미터 값을 출력
        default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.SQL: trace

server:
  port: {REVIEW_SERVICE_PORT}

eureka:
  client:
    service-url:
      defaultZone: {EUREKA_SERVER_URL}

cloud:
  aws:
    s3:
      bucket: {S3_BUCKET}
    credentials:
      access-key: {S3_ACCESS_KEY}
      secret-key: {S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false