spring:
    datasource:
      driver-class-name: org.postgresql.Driver
      username: takeit_review
      password: takeit_review
      url: jdbc:postgresql://postgres:5432/takeit_review
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          highlight_sql: true
          default_batch_fetch_size: 10
      open-in-view: false

server:
  port: 19096

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:19090/eureka/

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true