spring:
  datasource:
    url: ${REVIEW_DB_URL}
    username: ${REVIEW_DB_USERNAME}
    password: ${REVIEW_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${REVIEW_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 10
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

server:
  port: ${REVIEW_SERVICE_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}
  endpoint:
    health:
      show-details: when_authorized
    prometheus:
      enabled: true